services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mairu
      POSTGRES_PASSWORD: potemaru
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5555:5555
    volumes:
      - ./backend:/app

volumes:
  db:
