services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mairu
      POSTGRES_PASSWORD: potemaru
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5555:5555
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_USER_POOL_CLIENT_ID=${COGNITO_USER_POOL_CLIENT_ID}
  frontend-a:
    build:
      context: ./frontend-a
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend-a:/app
    environment:
      - NEXT_PUBLIC_USER_POOL_NAME=${COGNITO_USER_POOL_NAME}
      - NEXT_PUBLIC_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - NEXT_PUBLIC_USER_POOL_CLIENT_ID=${COGNITO_USER_POOL_CLIENT_ID}

volumes:
  db:
